// Offline cashier/manager PIN verification, matching apps/api/src/lib/pin.ts
// exactly (Node's crypto.scryptSync with default cost params: N=16384 (log2=14),
// r=8, p=1, keylen=64), stored as "salt:hash" hex. This has to run fully
// offline on the till (spec Section 6.1: "PIN login", zero network) against
// the pin_hash column already synced down via the `users` PowerSync stream -
// re-implemented in Rust rather than calling the server, since a manager
// override on a refund/void must work with no connectivity.
//
// Node treats a string `salt`/`password` argument to scryptSync via its
// default 'utf8' encoding - i.e. the salt used internally is the UTF-8
// BYTES of the 32-character hex STRING (32 bytes), not the 16 raw bytes you'd
// get by hex-decoding it. Confirmed empirically against a real hash Node
// generated (see verify_pin_matches_a_real_node_generated_hash below) -
// getting this wrong would silently reject every valid PIN.
use scrypt::Params;

const KEY_LENGTH: usize = 64;

fn scrypt_hex(pin: &str, salt_hex: &str) -> Result<String, String> {
    let params = Params::new(14, 8, 1).map_err(|e| e.to_string())?;
    let mut output = vec![0u8; KEY_LENGTH];
    scrypt::scrypt(pin.as_bytes(), salt_hex.as_bytes(), &params, &mut output)
        .map_err(|e| e.to_string())?;
    Ok(hex::encode(output))
}

/// `stored` is the "salt:hash" format written by hashPin() in
/// apps/api/src/lib/pin.ts (and synced down as the `pin_hash` column).
pub fn verify_pin(pin: &str, stored: &str) -> bool {
    let Some((salt_hex, expected_hash)) = stored.split_once(':') else {
        return false;
    };
    match scrypt_hex(pin, salt_hex) {
        Ok(actual_hash) => {
            // Constant-time-ish compare via hex round-trip length check first,
            // then byte comparison - full timing-attack hardening isn't the
            // priority for a 4-6 digit till PIN checked locally, correctness is.
            actual_hash.len() == expected_hash.len() && actual_hash == expected_hash
        }
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verify_pin_matches_a_real_node_generated_hash() {
        // Generated by the actual apps/api/src/lib/pin.ts hashPin('1234')
        // implementation (node -e scryptSync('1234', salt, 64)), not
        // fabricated - this is the exact compatibility check that matters.
        let stored = "074317f983fd46a6cb28fb0f80d4ed32:719a4604e1c8013c27a41dece393c53c87d6099e2410d858523c02b04051121f19b654dfba36c983a24ad2a67a9fe7bb0ee67898cf1c9272f2d99db910bad33d";
        assert!(verify_pin("1234", stored));
    }

    #[test]
    fn rejects_the_wrong_pin_against_the_same_hash() {
        let stored = "074317f983fd46a6cb28fb0f80d4ed32:719a4604e1c8013c27a41dece393c53c87d6099e2410d858523c02b04051121f19b654dfba36c983a24ad2a67a9fe7bb0ee67898cf1c9272f2d99db910bad33d";
        assert!(!verify_pin("9999", stored));
    }

    #[test]
    fn rejects_a_malformed_stored_value() {
        assert!(!verify_pin("1234", "not-the-right-format"));
    }
}
