/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'platform-admins': PlatformAdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'platform-admins': PlatformAdmin;
    tenants: Tenant;
    stores: Store;
    users: User;
    products: Product;
    'store-product-overrides': StoreProductOverride;
    'stock-movements': StockMovement;
    orders: Order;
    'purchase-orders': PurchaseOrder;
    suppliers: Supplier;
    'stock-transfers': StockTransfer;
    customers: Customer;
    'sync-log': SyncLog;
    shifts: Shift;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'platform-admins': PlatformAdminsSelect<false> | PlatformAdminsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'store-product-overrides': StoreProductOverridesSelect<false> | StoreProductOverridesSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'purchase-orders': PurchaseOrdersSelect<false> | PurchaseOrdersSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'stock-transfers': StockTransfersSelect<false> | StockTransfersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'sync-log': SyncLogSelect<false> | SyncLogSelect<true>;
    shifts: ShiftsSelect<false> | ShiftsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: PlatformAdmin | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PlatformAdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-admins".
 */
export interface PlatformAdmin {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'platform-admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  subscriptionTier: 'trial' | 'starter' | 'growth' | 'enterprise';
  billingStatus: 'active' | 'trialing' | 'past_due' | 'canceled';
  /**
   * Printed at the top of every receipt, below the business name (e.g. address, phone).
   */
  receiptHeader?: string | null;
  /**
   * Printed at the bottom of every receipt (e.g. "Thank you for your business!", return policy).
   */
  receiptFooter?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: number;
  tenant: number | Tenant;
  name: string;
  address?: string | null;
  timezone: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  tenant: number | Tenant;
  store?: (number | null) | Store;
  role: 'owner' | 'manager' | 'cashier';
  /**
   * A banned staff member cannot log in - password or till PIN - anywhere, on any device.
   */
  status: 'active' | 'banned';
  /**
   * Displayed at the till instead of the staff member's email.
   */
  name?: string | null;
  /**
   * e.g. 0712345678 - used for fast PIN login at the till.
   */
  phone?: string | null;
  /**
   * Fast till PIN login (4-6 digits). Never stored in plaintext.
   */
  pin?: string | null;
  pinHash?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant: number | Tenant;
  sku: string;
  barcode?: string | null;
  name: string;
  category?: string | null;
  variants?:
    | {
        label: string;
        sku: string;
        barcode?: string | null;
        id?: string | null;
      }[]
    | null;
  costPrice: number;
  sellPrice: number;
  taxRate: number;
  /**
   * Maximum % a cashier may discount this product at the till. 0 = no discount allowed.
   */
  maxDiscountPercent: number;
  /**
   * Dashboard flags this product as low-stock per store once on-hand quantity drops to or below this.
   */
  reorderPoint: number;
  isBundle?: boolean | null;
  bundleComponents?:
    | {
        product: number | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-product-overrides".
 */
export interface StoreProductOverride {
  id: number;
  tenant: number | Tenant;
  store: number | Store;
  product: number | Product;
  priceOverride?: number | null;
  isAvailable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: string;
  tenant: number | Tenant;
  store: number | Store;
  product: number | Product;
  variant?: string | null;
  /**
   * Positive = restock/return. Negative = sale/write-off.
   */
  quantityDelta: number;
  reason: 'sale' | 'restock' | 'transfer_in' | 'transfer_out' | 'adjustment' | 'write_off';
  relatedOrder?: (string | null) | Order;
  clientTimestamp: string;
  serverTimestamp?: string | null;
  sourceTerminal: string;
  flaggedForReview?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  tenant: number | Tenant;
  store: number | Store;
  terminal: string;
  terminalName?: string | null;
  cashier: number | User;
  customer?: (number | null) | Customer;
  /**
   * 1 point per 100 spent, server-computed at sale time. Stored (not recomputed) so a refund/void reverses exactly what was earned.
   */
  loyaltyPointsEarned?: number | null;
  lineItems: {
    product: number | Product;
    variant?: string | null;
    quantity: number;
    unitPrice: number;
    discount: number;
    id?: string | null;
  }[];
  taxTotal: number;
  discountTotal: number;
  total: number;
  tenderType: 'cash' | 'mpesa' | 'card' | 'credit';
  paymentStatus: 'paid' | 'pending' | 'failed';
  settledAt?: string | null;
  settledBy?: (number | null) | User;
  mpesaCheckoutRequestId?: string | null;
  pesapalOrderTrackingId?: string | null;
  status: 'completed' | 'refunded' | 'voided';
  createdOffline?: boolean | null;
  syncedAt?: string | null;
  kraInvoiceNumber?: string | null;
  kraQrCode?: string | null;
  kraCuSerial?: string | null;
  kraSubmissionStatus: 'not_applicable' | 'pending' | 'submitted' | 'failed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenant: number | Tenant;
  name: string;
  phone?: string | null;
  email?: string | null;
  loyaltyPoints: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-orders".
 */
export interface PurchaseOrder {
  id: number;
  tenant: number | Tenant;
  store: number | Store;
  supplier: number | Supplier;
  lineItems: {
    product: number | Product;
    quantity: number;
    unitCost: number;
    id?: string | null;
  }[];
  status: 'draft' | 'sent' | 'received';
  receivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  tenant: number | Tenant;
  name: string;
  contactInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-transfers".
 */
export interface StockTransfer {
  id: number;
  tenant: number | Tenant;
  fromStore: number | Store;
  toStore: number | Store;
  lineItems: {
    product: number | Product;
    quantity: number;
    id?: string | null;
  }[];
  status: 'draft' | 'in_transit' | 'received';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-log".
 */
export interface SyncLog {
  id: number;
  terminal: string;
  lastSyncedAt: string;
  pendingCount: number;
  conflictCount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shifts".
 */
export interface Shift {
  id: number;
  tenant: number | Tenant;
  store: number | Store;
  terminal: string;
  cashier: number | User;
  openedAt: string;
  openingFloat: number;
  closedAt?: string | null;
  closingCashCounted?: number | null;
  /**
   * openingFloat + all cash sales during this shift (server-computed on close).
   */
  expectedCash?: number | null;
  /**
   * closingCashCounted - expectedCash. Never auto-corrected - a manager reviews any non-zero variance.
   */
  variance?: number | null;
  status: 'open' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  tenant: number | Tenant;
  actor: number | User;
  action:
    | 'price_changed'
    | 'order_voided'
    | 'order_refunded'
    | 'sale_settled'
    | 'login'
    | 'login_blocked'
    | 'staff_created'
    | 'staff_banned'
    | 'staff_reactivated'
    | 'staff_deleted'
    | 'store_created'
    | 'store_deleted';
  entityType: 'product' | 'order' | 'user' | 'store';
  entityId: string;
  summary: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'platform-admins';
        value: number | PlatformAdmin;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'stores';
        value: number | Store;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'store-product-overrides';
        value: number | StoreProductOverride;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: string | StockMovement;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'purchase-orders';
        value: number | PurchaseOrder;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'stock-transfers';
        value: number | StockTransfer;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'sync-log';
        value: number | SyncLog;
      } | null)
    | ({
        relationTo: 'shifts';
        value: number | Shift;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'platform-admins';
        value: number | PlatformAdmin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'platform-admins';
        value: number | PlatformAdmin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-admins_select".
 */
export interface PlatformAdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  subscriptionTier?: T;
  billingStatus?: T;
  receiptHeader?: T;
  receiptFooter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  address?: T;
  timezone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenant?: T;
  store?: T;
  role?: T;
  status?: T;
  name?: T;
  phone?: T;
  pin?: T;
  pinHash?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  sku?: T;
  barcode?: T;
  name?: T;
  category?: T;
  variants?:
    | T
    | {
        label?: T;
        sku?: T;
        barcode?: T;
        id?: T;
      };
  costPrice?: T;
  sellPrice?: T;
  taxRate?: T;
  maxDiscountPercent?: T;
  reorderPoint?: T;
  isBundle?: T;
  bundleComponents?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-product-overrides_select".
 */
export interface StoreProductOverridesSelect<T extends boolean = true> {
  tenant?: T;
  store?: T;
  product?: T;
  priceOverride?: T;
  isAvailable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  id?: T;
  tenant?: T;
  store?: T;
  product?: T;
  variant?: T;
  quantityDelta?: T;
  reason?: T;
  relatedOrder?: T;
  clientTimestamp?: T;
  serverTimestamp?: T;
  sourceTerminal?: T;
  flaggedForReview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  id?: T;
  tenant?: T;
  store?: T;
  terminal?: T;
  terminalName?: T;
  cashier?: T;
  customer?: T;
  loyaltyPointsEarned?: T;
  lineItems?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        unitPrice?: T;
        discount?: T;
        id?: T;
      };
  taxTotal?: T;
  discountTotal?: T;
  total?: T;
  tenderType?: T;
  paymentStatus?: T;
  settledAt?: T;
  settledBy?: T;
  mpesaCheckoutRequestId?: T;
  pesapalOrderTrackingId?: T;
  status?: T;
  createdOffline?: T;
  syncedAt?: T;
  kraInvoiceNumber?: T;
  kraQrCode?: T;
  kraCuSerial?: T;
  kraSubmissionStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-orders_select".
 */
export interface PurchaseOrdersSelect<T extends boolean = true> {
  tenant?: T;
  store?: T;
  supplier?: T;
  lineItems?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitCost?: T;
        id?: T;
      };
  status?: T;
  receivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  contactInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-transfers_select".
 */
export interface StockTransfersSelect<T extends boolean = true> {
  tenant?: T;
  fromStore?: T;
  toStore?: T;
  lineItems?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  phone?: T;
  email?: T;
  loyaltyPoints?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-log_select".
 */
export interface SyncLogSelect<T extends boolean = true> {
  terminal?: T;
  lastSyncedAt?: T;
  pendingCount?: T;
  conflictCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shifts_select".
 */
export interface ShiftsSelect<T extends boolean = true> {
  tenant?: T;
  store?: T;
  terminal?: T;
  cashier?: T;
  openedAt?: T;
  openingFloat?: T;
  closedAt?: T;
  closingCashCounted?: T;
  expectedCash?: T;
  variance?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  tenant?: T;
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  summary?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}